//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swift.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTypeMList
    {
        public int DocumentTypeId { get; set; }
        public decimal BranchId { get; set; }
        public int Yr { get; set; }
        public int LastId { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
