//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swift.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsList
    {
        public decimal UID { get; set; }
        public decimal Transactions_UID { get; set; }
        public decimal ItemsM_UID { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public decimal BasicValue { get; set; }
        public decimal AddPer { get; set; }
        public decimal AddAmount { get; set; }
        public decimal BasicDiscountPer { get; set; }
        public decimal BasicDiscountAmount { get; set; }
        public decimal PackingPer { get; set; }
        public decimal PackingAmount { get; set; }
        public decimal ExciseDutyPer { get; set; }
        public decimal ExciseDutyAmount { get; set; }
        public decimal CessPer { get; set; }
        public decimal CessAmount { get; set; }
        public decimal LocalSalesTaxPer { get; set; }
        public decimal LocalSalesTaxAmount { get; set; }
        public decimal SurchargePer { get; set; }
        public decimal SurchargeAmount { get; set; }
        public decimal OtherSalesTaxPer { get; set; }
        public decimal OtherSalesTaxAmount { get; set; }
        public decimal ServiceTaxPer { get; set; }
        public decimal ServiceTaxAmount { get; set; }
        public decimal ServiceTaxCessPer { get; set; }
        public decimal ServiceTaxCessAmount { get; set; }
        public decimal TotalValue { get; set; }
        public Nullable<decimal> SalesVolumeDiscount { get; set; }
        public decimal Commission { get; set; }
        public decimal SpecialDiscount { get; set; }
        public int StatusM_UID { get; set; }
        public string AddlDetails { get; set; }
        public decimal UOM_UID { get; set; }
        public decimal RefTransactionsList_UID { get; set; }
        public decimal BalanceQty { get; set; }
        public decimal QtyDC { get; set; }
        public decimal QtyReceived { get; set; }
        public decimal QtyRejected { get; set; }
        public decimal QtyReworked { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public decimal Weight { get; set; }
        public decimal ExciseGroupM_UID { get; set; }
        public decimal ItemsM_Tolerance { get; set; }
        public decimal CategoryM_UID { get; set; }
        public decimal Sales_AccountM_UID { get; set; }
        public decimal Stock_AccountM_UID { get; set; }
        public decimal Consumption_AccountM_UID { get; set; }
        public decimal WIP_AccountM_UID { get; set; }
        public decimal ConversionUOM_UID { get; set; }
        public decimal ConversionUOM_Rate { get; set; }
        public decimal ConversionUOM_Qty { get; set; }
        public string BatchNo { get; set; }
        public decimal CommissionM_UID { get; set; }
        public decimal CommissionPer { get; set; }
        public decimal PartyMItemsMPrice_UID { get; set; }
        public Nullable<System.DateTime> WarrantyUpto { get; set; }
        public decimal ParentTransactionsList_UID { get; set; }
        public int RefDocumentTypeId { get; set; }
        public bool IsEDIncluded { get; set; }
        public decimal HECessPer { get; set; }
        public decimal HECessAmount { get; set; }
        public bool IsVATApplicable { get; set; }
        public bool IsEDApplicable { get; set; }
        public decimal StockValue { get; set; }
        public decimal EDID { get; set; }
        public decimal CessID { get; set; }
        public decimal HECessID { get; set; }
        public decimal VATID { get; set; }
        public decimal CSTID { get; set; }
        public decimal BalanceRejectedQty { get; set; }
        public decimal VATCategoryID { get; set; }
        public decimal TransactionsListSent_UID { get; set; }
        public decimal InspectionUID { get; set; }
        public decimal ServiceTaxID { get; set; }
        public Nullable<bool> IsRateCalForRecQty { get; set; }
        public Nullable<bool> IsAlternateBOM { get; set; }
        public Nullable<decimal> GRN_AccountM_UID { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
