//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swift.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsListDely
    {
        public decimal UID { get; set; }
        public decimal TransactionsList_UID { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<decimal> DeliveryQty { get; set; }
        public Nullable<decimal> BalanceJobCardQty { get; set; }
        public Nullable<decimal> ProductionQty { get; set; }
        public Nullable<decimal> DespatchedQty { get; set; }
        public Nullable<decimal> OrderedQty { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public int StatusM_UID { get; set; }
        public Nullable<System.DateTime> PackingDate { get; set; }
    
        public virtual TransactionsList TransactionsList { get; set; }
    }
}
