//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swift.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCustomerDetail
    {
        public decimal UID { get; set; }
        public string AccountName { get; set; }
        public string GSTIN { get; set; }
        public decimal AccountM_UID { get; set; }
        public string AccountCode { get; set; }
        public string Category { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string PANNo { get; set; }
        public string Fax { get; set; }
        public string email { get; set; }
        public decimal Debit_CreditLimit { get; set; }
        public int Debit_CreditDays { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string Pincode { get; set; }
        public string ExecutiveName { get; set; }
    }
}
